# https://rust-lang.github.io/rustfmt/

# https://github.com/rust-lang/rustfmt/tree/main/Configurations.md#edition
edition = "2024"

# https://github.com/rust-lang/rustfmt/tree/main/Configurations.md#hard_tabs
hard_tabs = true
