# static-web-server configuration for the Web Server
#
# References,
# - https://static-web-server.net/configuration/config-file/


[general]
host = "::"
root = "./assets"
# https://static-web-server.net/features/metrics/
metrics = true
